#*****************************************************************************************
# Vivado (TM) v2017.4 (64-bit)
#
# build.tcl: Tcl script for re-creating project 'adaptive_noise_cancellation'
#
# Generated by Vivado on Thu Jul 26 22:23:30 -0700 2018
# IP Build 2085800 on Fri Dec 15 22:25:07 MST 2017
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (build.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/imports/hdl/ADAU1761_interface.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/imports/hdl/adau1761_configuraiton_data.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/imports/hdl/adau1761_izedboard.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/imports/hdl/clocking.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/imports/hdl/i2c.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/imports/hdl/i2s_data_interface.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/imports/hdl/i3c2.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/imports/hdl/audio_top.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/imports/AudioInOut16_1.0/hdl/AudioInOut16_v1_0_S00_AXI.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/imports/AudioInOut16_1.0/src/DualClockFIFO.vhdl"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/imports/AudioInOut16_1.0/src/GrayCounter.vhdl"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/imports/AudioInOut16_1.0/hdl/AudioInOut16_v1_0.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/imports/new/pmod_i2s.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/new/source_mux.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/new/filter_control.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/bd/design_1/design_1.bd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/new/signal_multiplexer.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/imports/vhdl/nco_sine_lut_V.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/imports/vhdl/nco.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/imports/new/bit_shifter.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/new/adder_2.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/imports/vhdl/LMS_pkg.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/imports/vhdl/LMS.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/new/adder.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/new/17_sig_to_24_sig.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/new/noise_mux.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/new/slow_clock.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/imports/Documents/noise_gen.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/imports/Documents/NbitSatAdder.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/new/simple_noise_filter.vhd"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/sources_1/bd/design_1/ip/design_1_ZedboardOLED_0_0/src/charLib/charLib.coe"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/constrs_1/imports/constraints/zed_audio.xdc"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/adaptive_noise_cancellation.srcs/constrs_1/imports/zedboard_master_XDC_RevC_D_v3/zedboard_master_XDC_RevC_D_v3.xdc"
#    "C:/Users/sbork/Downloads/Adaptive-Noise-Cancellation-master/Adaptive-Noise-Cancellation-master/Adaptive_Noise_Cancellation/design_1_wrapper_behav.wcfg"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set project_name "adaptive_noise_cancellation"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set project_name $::user_project_name
}

variable script_file
set script_file "build.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set project_name [lindex $::argv $i] }
      "--help"         { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Create project
create_project ${project_name} ./${project_name} -part xc7z020clg484-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
set_msg_config  -ruleid {1}  -id {VRFC 10-664}  -string {{ERROR: [VRFC 10-664] expression has 16 elements ; expected 24 [C:/Programming/Git/adaptive_noise_cancellation/adaptive_noise_cancellation.srcs/sources_1/new/lms_filter.vhd:52]}}  -suppress  -source 8


# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${project_name}.cache/ip" -objects $obj
set_property -name "part" -value "xc7z020clg484-1" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "VHDL" -objects $obj
set_property -name "target_language" -value "VHDL" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_FIFO XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
set obj [get_filesets sources_1]
set_property "ip_repo_paths" "[file normalize "$origin_dir/IP_Repository"]" $obj

# Rebuild user ip_repo's index before adding any source files
update_ip_catalog -rebuild

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/imports/hdl/ADAU1761_interface.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/imports/hdl/adau1761_configuraiton_data.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/imports/hdl/adau1761_izedboard.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/imports/hdl/clocking.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/imports/hdl/i2c.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/imports/hdl/i2s_data_interface.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/imports/hdl/i3c2.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/imports/hdl/audio_top.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/imports/AudioInOut16_1.0/hdl/AudioInOut16_v1_0_S00_AXI.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/imports/AudioInOut16_1.0/src/DualClockFIFO.vhdl"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/imports/AudioInOut16_1.0/src/GrayCounter.vhdl"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/imports/AudioInOut16_1.0/hdl/AudioInOut16_v1_0.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/imports/new/pmod_i2s.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/new/source_mux.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/new/filter_control.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/bd/design_1/design_1.bd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/new/signal_multiplexer.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/imports/vhdl/nco_sine_lut_V.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/imports/vhdl/nco.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/imports/new/bit_shifter.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/new/adder_2.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/imports/vhdl/LMS_pkg.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/imports/vhdl/LMS.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/new/adder.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/new/17_sig_to_24_sig.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/new/noise_mux.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/new/slow_clock.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/imports/Documents/noise_gen.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/imports/Documents/NbitSatAdder.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/new/simple_noise_filter.vhd"]"\
 "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/sources_1/bd/design_1/ip/design_1_ZedboardOLED_0_0/src/charLib/charLib.coe"]"\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "hdl/ADAU1761_interface.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "hdl/adau1761_configuraiton_data.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "hdl/adau1761_izedboard.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "hdl/clocking.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "hdl/i2c.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "hdl/i2s_data_interface.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "hdl/i3c2.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "hdl/audio_top.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "hdl/AudioInOut16_v1_0_S00_AXI.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "src/DualClockFIFO.vhdl"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "src/GrayCounter.vhdl"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "hdl/AudioInOut16_v1_0.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "new/pmod_i2s.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "new/source_mux.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "new/filter_control.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "design_1/design_1.bd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "is_locked" -value "1" -objects $file_obj
}

set file "hdl/design_1_wrapper.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "new/signal_multiplexer.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "vhdl/nco_sine_lut_V.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "vhdl/nco.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "new/bit_shifter.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "new/adder_2.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "vhdl/LMS_pkg.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "vhdl/LMS.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "new/adder.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "new/17_sig_to_24_sig.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "new/noise_mux.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "new/slow_clock.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "Documents/noise_gen.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "Documents/NbitSatAdder.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "new/simple_noise_filter.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "charLib/charLib.coe"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "used_in" -value "" -objects $file_obj
set_property -name "used_in_simulation" -value "0" -objects $file_obj
set_property -name "used_in_synthesis" -value "0" -objects $file_obj


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "design_1_wrapper" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/constrs_1/imports/constraints/zed_audio.xdc"]"
set file_imported [import_files -fileset constrs_1 $file]
set file "constraints/zed_audio.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/adaptive_noise_cancellation.srcs/constrs_1/imports/zedboard_master_XDC_RevC_D_v3/zedboard_master_XDC_RevC_D_v3.xdc"]"
set file_imported [import_files -fileset constrs_1 $file]
set file "zedboard_master_XDC_RevC_D_v3/zedboard_master_XDC_RevC_D_v3.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_constrs_file" -value "$proj_dir/$project_name.srcs/constrs_1/imports/constraints/zed_audio.xdc" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Import local files from the original project
set files [list \
 "[file normalize "$origin_dir/design_1_wrapper_behav.wcfg"]"\
]
set imported_files [import_files -fileset sim_1 $files]

# Set 'sim_1' fileset file properties for remote files
# None

# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "design_1_wrapper" -objects $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7z020clg484-1 -flow {Vivado Synthesis 2017} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2017" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "part" -value "xc7z020clg484-1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7z020clg484-1 -flow {Vivado Implementation 2017} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2017" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {

}
set obj [get_runs impl_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "part" -value "xc7z020clg484-1" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:$project_name"
